[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true

[program:gunicorn]
command=/opt/hashcat-wpa-server/venv/bin/gunicorn app:app --bind 127.0.0.1:8000 --workers 1 --timeout 300
directory=/opt/hashcat-wpa-server
user=root
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=LOG_CONSOLE="1",POTFILE_DISABLE="0"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true

[program:hashcat-brain]
command=/bin/bash /opt/hashcat-wpa-server/bash/start_hashcat_brain.sh
directory=/opt/hashcat-wpa-server
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
