#!/bin/sh
set -e

case "$1" in
    purge)
        rm -rf /opt/hashcat-wpa-server/venv
        rm -rf /var/lib/hashcat-wpa-server
        rm -rf /var/log/hashcat-wpa-server
        rm -f /usr/local/bin/crackserver
        rm -f /etc/sudoers.d/hashcat-tailscale
        
        systemctl daemon-reload >/dev/null 2>&1 || true
        
        if id "hashcat" >/dev/null 2>&1; then
            userdel hashcat || true
        fi
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
