#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if systemctl is-active --quiet hashcat-wpa-server.service; then
            systemctl stop hashcat-wpa-server.service
        fi
        if systemctl is-enabled --quiet hashcat-wpa-server.service; then
            systemctl disable hashcat-wpa-server.service
        fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
